sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t prathibha97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prathibha97/docker-react npm run test